### ISSUE TITLE
Any plans to add support for examples from CRD schemas?

### ISSUE THREAD

**Issue by gerhard** [seredot/kubectl-example#2]
Given a `rabbitmqcluster` CRD installed via https://github.com/rabbitmq/cluster-operator, rather than using `k explain rmq` to discover the schema, do you think that it would be a good idea to have `kubectl example rmq` generate an example based on this schema?

cc @mkuratczyk

**Comment by gerhard** [comment]
I've linked the exact context where I tried using it. [Larger context](https://github.com/rabbitmq/tgir/pull/18) & bird's eye view: [TGIR on YouTube](https://www.youtube.com/channel/UCSg9GRMGAo7euj3baJi4dOg/videos?view_as=subscriber).

**Comment by sahil-lakhwani** [comment]
hey @gerhard , if you're looking for a tool to generate examples from CRD schemas, you might want to check a plugin I wrote -  [kubectl-creyaml](https://github.com/sahil-lakhwani/kubectl-creyaml). It's also on krew.

**Comment by seredot** [comment]
@gerhard you may create an example in resources folder and create a PR.
